---
title: "Impute NA"
author: "Tianyi Fang"
date: "October 28, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Categorical features
```{r}
train <- read.csv("train_2016_v2.csv", header = TRUE, stringsAsFactors = FALSE)
property <- read.csv("rename_property_1.csv", header = TRUE, stringsAsFactors = FALSE)
train <- rename(train, c("parcelid"="id_parcel"))

property_1 <- subset(property, id_parcel %in% train$id_parcel)
ptrain <- merge(train, property_1, by = "id_parcel", all.x = TRUE)#left inner join
#GET NA 
#check # of unique in each feature
n_distinct(property$type_archit)
#check # of na
length(which(is.na(property$type_archit)))
#use n_distinct(pt$architecturalstyletypeid) in dplyr is faster and more concise than length(unique())

num.NA.pt <- sort(colSums(sapply(property, is.na)))
#check every feature, is there missing value
#sort(sapply(pt, function(x){sum(is.na(x))}), decreasing= TRUE)
na.df <- data.frame(num.NA.pt)
na.df$names <- rownames(na.df)

na.df%>%
  ggplot(aes(x=reorder(names, -num.NA.pt), y=num.NA.pt)) +
  geom_bar(stat="identity", fill="darkblue")+ labs(title="Number of NA of features", x="features", y="Amount of NA")+ theme(axis.text.x=element_text(angle=80, hjust = 1))
```
